#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2024, Manchester University (http://www.manchester.ac.uk/)
#
#     This work is made available under the Creative Commons
#     Attribution-ShareAlike 4.0 International licence.
#
#     For details of the licence terms see:
#     https://creativecommons.org/licenses/by-sa/4.0/
#   </meta:licence>
# </meta:header>
#
# AIMetrics: [
#     {
#     "name": "ChatGPT",
#     "contribution": {
#       "value": 5,
#       "units": "%"
#       }
#     }
#   ]
#

openapi: 3.1.0
info:
  title: IVOA ExecutionBroker log messages
  version: "1.0"
  summary: IVOA ExecutionBroker DockerContainer
  description: |
    OpenAPI schema for a Docker container in IVOA ExecutionBroker
  contact:
    name: Dave Morris
    url: https://github.com/Zarquan
  license:
    name: Creative Commons Attribution Share Alike 4.0 International
    identifier: CC-BY-SA-4.0

components:
  schemas:

    DockerContainer:
      description: |
        A Docker or OCI container executable.
        See https://opencontainers.org/
      type: object
      title: DockerContainer
      allOf:
        - $ref: '../../openapi.yaml#/components/schemas/AbstractExecutable'
        - type: object
          properties:
            image:
              ident:
                type: string
                description: |
                  The full image identifier, including repository, namespace and tag.
              name:
                type: string
                description: |
                  The full image name.
              namespace:
                type: string
                description: |
                  The namespace within the repository.
              tag:
                type: string
                description: |
                  The image tag.
              repository:
                type: string
                description: |
                  The respository hostname.
              platform:
                architecture:
                  type: string
                  description: |
                    The CPU architecture the image is built for.
                    The default is `amd64`.
                os:
                  type: string
                  description: |
                    The operating system the image is built for.
                    The default is `linux`.
              digest:
                type: string
                description: |
                  The image digest, generated as a as sha256 checksum when the image is built.
                  The unique digest can be used to verify the contents of a downloaded image.
            privileged:
              type: boolean
              default: false
              description: |
                Set the privileged flag on execution.
                The default is `false`.
                See https://docs.docker.com/reference/cli/docker/container/run/#privileged.
            entrypoint:
              type: string
              description: |
                Overwrite the default ENTRYPOINT of the image.
            environment:
              description: |
                A name => value map of environment variables to pass to the container.
              $ref: '../../components/utils.yaml#/components/schemas/NameValueMap'
            network:
              description: |
                Details of the network access available to the container.
              $ref: '#/components/schemas/DockerNetworkSpec'

    DockerNetworkSpec:
      description: |
        Details of the network access available to the container.
      type: object
      title: DockerNetworkSpec
      properties:
        ports:
          description: |
            An array of network ports to publish.
          type: array
          items:
            $ref: '#/components/schemas/DockerNetworkPort'

    DockerNetworkPort:
      description: |
        Details of a network port on the container made available for connection from outside.
      type: object
      title: DockerNetworkPort
      properties:
        address:
          type: string
          description: |
            The IP address of the external network interface.
            The client should not set this value.
            The service will update this with a publicly accessible interface address when it sets up the execution.
        external:
          type: string
          description: |
            The host machine's external port number to connect.
            The client should not set this value.
            The service will update this with the corrent port number when it sets up the execution.
        internal:
          type: string
          description: |
            The port number on the container to publish.
        protocol:
          type: string
          enum:
            - UDP
            - TCP
            - HTTP
            - HTTPS
          description: |
            The network protocol to use, default is `TCP`.
            The `HTTP` and `HTTPS` values further specify the Protocol to use on top of `TCP`.
            Specifying `HTTPS` may help to meet firewall restrictions at some sites.


